/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnAskRouteImport } from './routes/learn.ask'
import { Route as LearnPathRouteImport } from './routes/learn.path'
import { Route as LearnQuizRouteImport } from './routes/learn.quiz'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherCoursesRouteImport } from './routes/teacher.courses'
import { Route as TeacherEditorRouteImport } from './routes/teacher.editor'
import { Route as TeacherPipelineRouteImport } from './routes/teacher.pipeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAskRoute = LearnAskRouteImport.update({
  id: '/learn/ask',
  path: '/learn/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPathRoute = LearnPathRouteImport.update({
  id: '/learn/path',
  path: '/learn/path',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnQuizRoute = LearnQuizRouteImport.update({
  id: '/learn/quiz',
  path: '/learn/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherCoursesRoute = TeacherCoursesRouteImport.update({
  id: '/teacher/courses',
  path: '/teacher/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherEditorRoute = TeacherEditorRouteImport.update({
  id: '/teacher/editor',
  path: '/teacher/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPipelineRoute = TeacherPipelineRouteImport.update({
  id: '/teacher/pipeline',
  path: '/teacher/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn/ask': typeof LearnAskRoute
  '/learn/path': typeof LearnPathRoute
  '/learn/quiz': typeof LearnQuizRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/editor': typeof TeacherEditorRoute
  '/teacher/pipeline': typeof TeacherPipelineRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn/ask': typeof LearnAskRoute
  '/learn/path': typeof LearnPathRoute
  '/learn/quiz': typeof LearnQuizRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/editor': typeof TeacherEditorRoute
  '/teacher/pipeline': typeof TeacherPipelineRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn/ask': typeof LearnAskRoute
  '/learn/path': typeof LearnPathRoute
  '/learn/quiz': typeof LearnQuizRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/editor': typeof TeacherEditorRoute
  '/teacher/pipeline': typeof TeacherPipelineRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn/ask'
    | '/learn/path'
    | '/learn/quiz'
    | '/teacher/courses'
    | '/teacher/editor'
    | '/teacher/pipeline'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/learn/ask'
    | '/learn/path'
    | '/learn/quiz'
    | '/teacher/courses'
    | '/teacher/editor'
    | '/teacher/pipeline'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/learn/ask'
    | '/learn/path'
    | '/learn/quiz'
    | '/teacher/courses'
    | '/teacher/editor'
    | '/teacher/pipeline'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnAskRoute: typeof LearnAskRoute
  LearnPathRoute: typeof LearnPathRoute
  LearnQuizRoute: typeof LearnQuizRoute
  TeacherCoursesRoute: typeof TeacherCoursesRoute
  TeacherEditorRoute: typeof TeacherEditorRoute
  TeacherPipelineRoute: typeof TeacherPipelineRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/ask': {
      id: '/learn/ask'
      path: '/learn/ask'
      fullPath: '/learn/ask'
      preLoaderRoute: typeof LearnAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/path': {
      id: '/learn/path'
      path: '/learn/path'
      fullPath: '/learn/path'
      preLoaderRoute: typeof LearnPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/quiz': {
      id: '/learn/quiz'
      path: '/learn/quiz'
      fullPath: '/learn/quiz'
      preLoaderRoute: typeof LearnQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/courses': {
      id: '/teacher/courses'
      path: '/teacher/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/editor': {
      id: '/teacher/editor'
      path: '/teacher/editor'
      fullPath: '/teacher/editor'
      preLoaderRoute: typeof TeacherEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/pipeline': {
      id: '/teacher/pipeline'
      path: '/teacher/pipeline'
      fullPath: '/teacher/pipeline'
      preLoaderRoute: typeof TeacherPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnAskRoute: LearnAskRoute,
  LearnPathRoute: LearnPathRoute,
  LearnQuizRoute: LearnQuizRoute,
  TeacherCoursesRoute: TeacherCoursesRoute,
  TeacherEditorRoute: TeacherEditorRoute,
  TeacherPipelineRoute: TeacherPipelineRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
